[phases.setup]
nixPkgs = ["...", "python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt", "cd EduMorph && python -m pip install -r requirements.txt"]

[start]
cmd = "cd EduMorph && python src/api/run_server.py"
