[build]
builder = "NIXPACKS"
buildCommand = "cd EduMorph && pip install -r requirements.txt"

[deploy]
startCommand = "cd EduMorph && python src/api/run_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
